### ISSUE TITLE
(module name): issue aws.greengrass.clientdevices.Auth in broken state after deployment description

### ISSUE THREAD

**Issue by dbateamz** [aws-greengrass/aws-greengrass-client-device-auth#237]
**Short Bug Description**
aws.greengrass.clientdevices.Auth in broken state after deployment

**Current Config**
```
{
  "deviceGroups": {
    "formatVersion": "2021-03-05",
    "definitions": {
      "MyPermissiveDeviceGroup": {
        "selectionRule": "thingName: *",
        "policyName": "MyPermissivePolicy"
      }
    },
    "policies": {
      "MyPermissivePolicy": {
        "AllowAll": {
          "statementDescription": "Allow client devices to perform all actions.",
          "operations": [
            "*"
          ],
          "resources": [
            "*"
          ]
        }
      }
    }
  }
}
```

**Error Log**
```
[ERROR] (main) com.aws.greengrass.lifecyclemanager.Kernel: Cannot load service. {}
com.aws.greengrass.lifecyclemanager.exceptions.ServiceLoadException: Unable to load aws.greengrass.clientdevices.Auth as a plugin

 [ERROR] (pool-2-thread-21) com.aws.greengrass.deployment.DeploymentService: deployment-errored. {deploymentId=ca868e4b-25c5-4b7d-952d-7329e608437c, serviceName=DeploymentService, currentState=RUNNING}
com.aws.greengrass.deployment.exceptions.ServiceUpdateException: Service aws.greengrass.clientdevices.Auth in broken state after deployment
        at com.aws.greengrass.deployment.DeploymentConfigMerger.waitForServicesToStart(DeploymentConfigMerger.java:200)
        at com.aws.greengrass.deployment.KernelUpdateDeploymentTask.call(KernelUpdateDeploymentTask.java:67)
        at com.aws.greengrass.deployment.KernelUpdateDeploymentTask.call(KernelUpdateDeploymentTask.java:34)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

[ERROR] (pool-2-thread-11) com.aws.greengrass.deployment.DeploymentService: Deployment task failed with following errors. {DeploymentId=arn:aws:greengrass:us-west-2:602730180655:configuration:thing/GGCV2PIv3:1, >
com.aws.greengrass.deployment.exceptions.DeploymentException: Service aws.greengrass.clientdevices.Auth in broken state after deployment
        at com.aws.greengrass.deployment.KernelUpdateDeploymentTask.getDeploymentStatusDetails(KernelUpdateDeploymentTask.java:133)
        at com.aws.greengrass.deployment.KernelUpdateDeploymentTask.call(KernelUpdateDeploymentTask.java:74)
        at com.aws.greengrass.deployment.KernelUpdateDeploymentTask.call(KernelUpdateDeploymentTask.java:34)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
It typically happens after unexpected shutdown or reboot of the host device.

**Temporary workaround**
Remove Greengrass core and create new core device with the same configuration.

**Environment**
 - OS: Ubuntu 22.04 LTS
 - JDK version: 
Openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)
 - Nucleus version: 2.9.4
 - Client Device Auth version:  2.3.2

**Comment by MikeDombo** [comment]
The first error is the problem, please provide more context around it from the logs.

```
[ERROR] (main) com.aws.greengrass.lifecyclemanager.Kernel: Cannot load service. {}
com.aws.greengrass.lifecyclemanager.exceptions.ServiceLoadException: Unable to load aws.greengrass.clientdevices.Auth as a plugin
```

**Comment by dbateamz** [comment]
Hello Mike, please check out the attached log

[greengrass.log](https://github.com/aws-greengrass/aws-greengrass-client-device-auth/files/10959547/greengrass.log)

**Comment by MikeDombo** [comment]
Your problem is `Caused by: java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space`

Have you configured Greengrass to run with a java memory limit? If so, you must increase it.

**Comment by dbateamz** [comment]
That was it. Thank you for help!
